# Generated by Django 4.2.1 on 2023-05-09 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='category-images/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('casing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.casing')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('game_debate_name', models.CharField(max_length=244, null=True)),
                ('image', models.ImageField(null=True, upload_to='games-images/')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('subtitle', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('processor', models.CharField(max_length=100, null=True)),
                ('gpu', models.CharField(max_length=100, null=True)),
                ('ram', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(choices=[('hp', 'hp'), ('dell', 'dell'), ('lenovo', 'lenovo'), ('asus', 'asus'), ('msi', 'msi'), ('apple', 'apple')], max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='product-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('apartment', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postalCode', models.CharField(max_length=15, null=True)),
                ('emailNewsLetter', models.BooleanField(default=False)),
                ('saveInformation', models.BooleanField(default=False)),
                ('textNewsOffer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='sub-category-images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('value', models.CharField(max_length=244, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
        ),
        migrations.CreateModel(
            name='PreBuiltPerformanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='prebuilt-stats-images/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.games')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, null=True)),
                ('model', models.CharField(max_length=244, null=True)),
                ('price', models.CharField(max_length=244, null=True)),
                ('description', models.TextField(null=True)),
                ('casing_comaptible', models.ManyToManyField(related_name='casing_comaptible', to='api.casing')),
                ('gpu_compatible', models.ManyToManyField(related_name='gpu_compatible', to='api.ram')),
                ('powersupply_compatible', models.ManyToManyField(related_name='powersupply_compatible', to='api.ram')),
                ('processor_compatible', models.ManyToManyField(related_name='processor_compatible', to='api.processors')),
                ('ram_compatible', models.ManyToManyField(related_name='ram_compatible', to='api.ram')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product-images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBuildStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='custombuilt-stats-images/')),
                ('customBuild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.custombuild')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.games')),
            ],
        ),
        migrations.AddField(
            model_name='custombuild',
            name='graphics_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.graphicscard'),
        ),
        migrations.AddField(
            model_name='custombuild',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motherboard'),
        ),
        migrations.AddField(
            model_name='custombuild',
            name='power_Supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.powersupply'),
        ),
        migrations.AddField(
            model_name='custombuild',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processors'),
        ),
        migrations.AddField(
            model_name='custombuild',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ram'),
        ),
        migrations.AddField(
            model_name='custombuild',
            name='storage_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storagedrive'),
        ),
        migrations.AddField(
            model_name='custombuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
