# Generated by Django 4.2.1 on 2023-05-09 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='casing',
            name='image',
            field=models.ImageField(null=True, upload_to='casing-images/'),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='image',
            field=models.ImageField(null=True, upload_to='casing-images/'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='image',
            field=models.ImageField(null=True, upload_to='powersupply-images/'),
        ),
        migrations.AddField(
            model_name='processors',
            name='image',
            field=models.ImageField(null=True, upload_to='processor-images/'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(null=True, upload_to='ram-images/'),
        ),
        migrations.AddField(
            model_name='storagedrive',
            name='image',
            field=models.ImageField(null=True, upload_to='storage-images/'),
        ),
        migrations.CreateModel(
            name='ProductCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBuildCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('customBuild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.custombuild')),
            ],
        ),
    ]
