# Generated by Django 4.2.1 on 2023-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cooler_createorder_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='gpu_compatible',
            field=models.ManyToManyField(related_name='gpu_compatible', to='api.graphicscard'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='powersupply_compatible',
            field=models.ManyToManyField(related_name='powersupply_compatible', to='api.powersupply'),
        ),
    ]
