# Generated by Django 4.2.1 on 2023-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_motherboard_gpu_compatible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(null=True, upload_to='motherboard-images/'),
        ),
    ]
