# Generated by Django 4.2.1 on 2023-05-14 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_motherboard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='casing-images/')),
                ('casing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.casing')),
            ],
        ),
    ]
