# Generated by Django 4.2.1 on 2023-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_performancescrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescrape',
            name='cpu',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='performancescrape',
            name='game',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='performancescrape',
            name='gpu',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='performancescrape',
            name='ram',
            field=models.CharField(max_length=244, null=True),
        ),
    ]
